### ISSUE TITLE
Passing around procs confuses CPS

### ISSUE THREAD

**Issue by zevv** [disruptek/cps#208] opened 2021-07-16 19:43 UTC
This works not:
```
import cps

type C = Continuation

proc foo(fn: proc(): string) {.cps:C.} =
  echo fn()
  
proc bar() {.cps:C.} =
  foo(proc(): string = "hello")
  
bar()
```
telling me:

```
/tmp/t.nim(9, 14) template/generic instantiation of `cps` from here
/tmp/t.nim(10, 6) Error: type mismatch: got <void>
but expected one of: 
proc foo(fn: proc (): string)
  first type mismatch at position: 1
  required type for fn: proc (): string{.closure.}
  but expression 'proc (): string = result = "hello"' is of type: void

expression: foo(proc (): string = result = "hello")
```

Note that removing the `{.cps:C.}` from `foo()` and `bar()` makes this perfectly valid.

**Comment by disruptek** [comment] 2021-07-16 22:47
Thanks for confirming that returning a string from a nullary proc is still a thing that works in Nim.  Sometimes it's nice to be reminded of everything that still works.

Cool bug though, thanks.

**Comment by disruptek** [comment] 2021-08-08 22:51
Duplicate of #185.

**Closed by disruptek** 2021-08-08 22:51 UTC
Labels: bug, nim compiler defect
